---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mariadb-operator
  template:
    metadata:
      labels:
        name: mariadb-operator
    spec:
      serviceAccountName: mariadb-operator
      containers:
        - name: ansible
          command:
            - /usr/local/bin/ao-logs
            - /tmp/ansible-operator/runner
            - stdout
          image: "{{ operator_image }}"
          imagePullPolicy: "{{ pull_policy|default('Always') }}"
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
              readOnly: true
        - name: operator
          image: "{{ operator_image }}"
          imagePullPolicy: "{{ pull_policy|default('Always') }}"
          volumeMounts:
            - mountPath: /tmp/ansible-operator/runner
              name: runner
          env:
            # Watch all namespaces (cluster-scoped).
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "mariadb-operator"
      volumes:
        - name: runner
          emptyDir: {}
